/*
3474. Lexicographically Smallest Generated String
You are given two strings, str1 and str2, of lengths n and m, respectively.
A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

Example 1:
Input: str1 = "TFTF", str2 = "ab"
Output: "ababa"
Explanation:
The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.
Return "ababa" since it is the lexicographically smaller string.

Example 2:
Input: str1 = "TFTF", str2 = "abc"
Output: ""
Explanation:
No string that satisfies the conditions can be generated.

Example 3:
Input: str1 = "F", str2 = "d"
Output: "a"

Constraints:
1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
*/

#include<iostream>
#include<vector>
using namespace std;

string generateString(string str1, string str2) {
    int n = str1.size();
    int m = str2.size();
    string s(n + m - 1, 'a');
    vector<bool> fixed(n + m - 1, false);
    for(int i = 0; i < n; ++i){
        if(str1[i] == 'T'){
            for(int j = 0; j < m; ++j){
                int pos = i + j;
                if(fixed[pos] && s[pos] != str2[j]) return "";
                s[pos] = str2[j];
                fixed[pos] = true;
            }
        }
    }
    for(int i = 0; i < n; ++i){
        if(str1[i] == 'F'){
            bool diff = false;
            for(int j = 0; j < m; j++){
                if(s[i + j] != str2[j]){
                    diff = true;
                    break;
                }
            }
            if(diff){
                continue;
            }
            bool changed = false;
            for(int j = m - 1; j >= 0; j--){
                if(fixed[i + j] == false){
                    s[i + j] = 'b';
                    changed = true;
                    break;
                }
            }
            if(!changed){
                return "";
            }
        }
    }
    return s;
}

int main(){
    string str1, str2;
    cin >> str1 >> str2;
    string result = generateString(str1, str2);
    if(result.empty()){
        cout << "No valid string can be generated." << endl;
    } else {
        cout << "Generated string: " << result << endl;
    }
    return 0;
}
